### ISSUE TITLE
popover=true attribute conflicts with Popover API

### ISSUE THREAD

**Issue by szmalec** [vitalets/angular-xeditable#786]
@vitalets It seems that ["Editable ui-bootstrap Popover"](http://vitalets.github.io/angular-xeditable/#uipopover) does not work in Chrome 114.0.5735.91 - probably due to new [Popover API](https://developer.chrome.com/blog/introducing-popover-api/) (see also [here](https://github.com/GoogleChrome/developer.chrome.com/blob/main/site/en/blog/introducing-popover-api/index.md))... It's just that the `popover=true` attribute conflicts with [the attribute of this new Chrome API](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/popover)... In Chrome Developer Tools we can see that `<a ... popover="true">...</a>` has additional `user agent stylesheet` applied:

```css
[popover]:not(:popover-open):not(dialog[open]) {
    display: none;
}
[popover] {
    position: fixed;
    width: fit-content;
    height: fit-content;
    color: canvastext;
    background-color: canvas;
    inset: 0px;
    margin: auto;
    border-width: initial;
    border-style: solid;
    border-color: initial;
    border-image: initial;
    padding: 0.25em;
    overflow: auto;
}
```

Is there any chance to solve this problem in angular-xeditable? Regards!
